-- 0020_seed_mock_test.sql
-- BUET Prep AI — Bahria University Extended Mock Test
-- 150 MCQs | 120 minutes | 1 mark each | no negative marking
-- Sections: 1 Verbal Ability (44) | 2 Quantitative Reasoning (23) | 3 Analytical Reasoning (22)
--           4 Physics (15) | 5 Mathematics (45) | 6 Number System (1)
-- Seeds the mock questions, the mock_tests row, and the mock_test_questions links.
-- All questions are original practice items (ORIGINAL_AI, approved), each with exactly 4 options.

-- =============================================================
-- MOCK QUESTION SEEDER (inserts question + options + mock link)
-- =============================================================
create or replace function "public"."seed_mock_question"(
  p_mock_name text,
  p_mock_desc text,
  p_section integer,
  p_order integer,
  p_subject_code text,
  p_topic_name text,
  p_difficulty "public"."difficulty",
  p_question text,
  p_correct "char",
  p_a text, p_b text, p_c text, p_d text,
  p_explanation text
) returns void language plpgsql as $$
declare
  m_id uuid;
  q_id uuid;
  opt text[];
  keys text[] := array['A','B','C','D'];
  i int;
begin
  select id into m_id from "public"."mock_tests" where name = p_mock_name limit 1;
  if m_id is null then
    insert into "public"."mock_tests" (name, description, is_active, question_count, duration_minutes)
    values (p_mock_name, p_mock_desc, true, 150, 120)
    returning id into m_id;
  end if;

  select id into q_id from "public"."questions"
  where lower(trim(question_text)) = lower(trim(p_question)) limit 1;
  if q_id is null then
    insert into "public"."questions"
      (subject_id, topic_id, difficulty, question_text, correct_option, explanation, solution_steps, hint,
       is_original, is_official_sample, review_status, generated_by, source_type, source_reference, copyright_status, reviewed)
    values
      ((select id from "public"."subjects" where code = p_subject_code),
       (select id from "public"."topics" where subject_id = (select id from "public"."subjects" where code = p_subject_code) and name = p_topic_name),
       p_difficulty, p_question, p_correct, p_explanation, '[]'::jsonb, null,
       true, false, 'approved', 'AI', 'ORIGINAL_AI',
       'Original AI-generated mock test question', 'original', true)
    returning id into q_id;

    opt := array[p_a, p_b, p_c, p_d];
    for i in 1..4 loop
      insert into "public"."question_options" (question_id, option_key, option_text, is_correct, order_index)
      values (q_id, keys[i], opt[i], (keys[i] = p_correct), i - 1);
    end loop;

    insert into "public"."question_sources" (question_id, source_type, source_reference, copyright_status, is_original)
    values (q_id, 'ORIGINAL_AI', 'Original AI-generated mock test question', 'original', true);
  end if;

  insert into "public"."mock_test_questions" (mock_test_id, question_id, section_index, order_index)
  values (m_id, q_id, p_section, p_order)
  on conflict (mock_test_id, question_id) do nothing;
end;
$$;

-- =============================================================
-- SEED ALL 150 QUESTIONS
-- =============================================================
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 1, $$ENG$$, $$Vocabulary$$, $$easy$$, $$The word "abundant" is closest in meaning to:$$, 'B', $$scarce$$, $$plentiful$$, $$hidden$$, $$fragile$$, $$Abundant means existing in large quantities; plentiful is its nearest synonym.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 2, $$ENG$$, $$Vocabulary$$, $$easy$$, $$The word "reluctant" means:$$, 'B', $$eager$$, $$unwilling$$, $$careless$$, $$certain$$, $$Reluctant describes someone unwilling or hesitant to do something.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 3, $$ENG$$, $$Vocabulary$$, $$easy$$, $$The antonym of "ancient" is:$$, 'C', $$old$$, $$historic$$, $$modern$$, $$former$$, $$Ancient refers to something very old; modern is its direct opposite.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 4, $$ENG$$, $$Vocabulary$$, $$easy$$, $$The antonym of "expand" is:$$, 'B', $$increase$$, $$contract$$, $$develop$$, $$extend$$, $$Expand means to grow larger; contract means to shrink or reduce.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 5, $$ENG$$, $$Vocabulary$$, $$easy$$, $$Choose the word closest in meaning to "precise":$$, 'A', $$exact$$, $$rough$$, $$late$$, $$complex$$, $$Precise means exact and accurate.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 6, $$ENG$$, $$Vocabulary$$, $$medium$$, $$A person who writes dictionaries is called a:$$, 'B', $$biographer$$, $$lexicographer$$, $$geologist$$, $$cartographer$$, $$A lexicographer compiles and writes dictionaries.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 7, $$ENG$$, $$Vocabulary$$, $$medium$$, $$"Benevolent" most nearly means:$$, 'A', $$kind$$, $$angry$$, $$wealthy$$, $$famous$$, $$Benevolent means kind, charitable, or well-meaning.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 8, $$ENG$$, $$Vocabulary$$, $$medium$$, $$"Obsolete" means:$$, 'A', $$outdated$$, $$original$$, $$necessary$$, $$popular$$, $$Obsolete means no longer in use or outdated.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 9, $$ENG$$, $$Vocabulary$$, $$medium$$, $$"Candid" most nearly means:$$, 'B', $$secretive$$, $$frank$$, $$confused$$, $$formal$$, $$Candid means frank, honest, and straightforward.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 10, $$ENG$$, $$Vocabulary$$, $$medium$$, $$"Deteriorate" means to:$$, 'B', $$improve$$, $$worsen$$, $$repeat$$, $$measure$$, $$Deteriorate means to become progressively worse.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 11, $$ENG$$, $$Grammar$$, $$easy$$, $$Choose the correct sentence:$$, 'B', $$Neither of the boys are ready.$$, $$Neither of the boys is ready.$$, $$Neither of the boys were ready.$$, $$Neither boys is ready.$$, $$With "neither of", the verb must agree with the singular pronoun; "is" is correct.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 12, $$ENG$$, $$Grammar$$, $$easy$$, $$Choose the correct form: "She _____ to school every day."$$, 'C', $$go$$, $$going$$, $$goes$$, $$gone$$, $$Third-person singular simple present requires "goes".$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 13, $$ENG$$, $$Grammar$$, $$medium$$, $$If I _____ enough money, I would buy a laptop.$$, 'B', $$have$$, $$had$$, $$will have$$, $$having$$, $$Second conditional uses past subjunctive "had" after "If".$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 14, $$ENG$$, $$Grammar$$, $$easy$$, $$Choose the correctly punctuated sentence:$$, 'B', $$However I decided to stay.$$, $$However, I decided to stay.$$, $$However I, decided to stay.$$, $$However; I decided, to stay.$$, $$A conjunctive adverb like "However" is followed by a comma.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 15, $$ENG$$, $$Grammar$$, $$medium$$, $$The plural of "criterion" is:$$, 'B', $$criterions$$, $$criteria$$, $$criterion$$, $$criterias$$, $$"Criterion" is a Greek-origin noun; its plural is "criteria".$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 16, $$ENG$$, $$Active-Passive Voice$$, $$easy$$, $$Which sentence is in passive voice?$$, 'B', $$Ali solved the problem.$$, $$The problem was solved by Ali.$$, $$Ali is solving the problem.$$, $$Ali will solve the problem.$$, $$Passive voice pairs "was + past participle"; the doer appears after "by".$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 17, $$ENG$$, $$Prepositions$$, $$easy$$, $$Choose the correct preposition: "He is good _____ mathematics."$$, 'C', $$in$$, $$on$$, $$at$$, $$for$$, $$We say "good at" an activity or subject.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 18, $$ENG$$, $$Articles$$, $$easy$$, $$Choose the correct article: "He is _____ honest man."$$, 'B', $$a$$, $$an$$, $$the$$, $$no article$$, $$"Honest" begins with a vowel sound, so it takes "an".$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 19, $$ENG$$, $$Grammar$$, $$easy$$, $$Which word is an adverb?$$, 'B', $$quick$$, $$quickly$$, $$quicker$$, $$quickness$$, $$Adverbs often end in -ly; "quickly" modifies a verb.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 20, $$ENG$$, $$Grammar$$, $$easy$$, $$Choose the correct sentence:$$, 'B', $$Each student have a book.$$, $$Each student has a book.$$, $$Each students has a book.$$, $$Each student having a book.$$, $$"Each" is singular, so the verb must be "has".$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 21, $$ENG$$, $$Sentence Completion$$, $$medium$$, $$Although the road was difficult, the driver _____ the journey.$$, 'B', $$abandoned$$, $$completed$$, $$prevented$$, $$forgot$$, $$"Although" signals contrast, so the driver succeeded: completed.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 22, $$ENG$$, $$Sentence Completion$$, $$easy$$, $$The lecture was so _____ that everyone remained attentive.$$, 'B', $$dull$$, $$engaging$$, $$weak$$, $$brief$$, $$Remaining attentive is caused by an engaging lecture.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 23, $$ENG$$, $$Sentence Completion$$, $$medium$$, $$Because the evidence was insufficient, the case was _____.$$, 'B', $$accepted$$, $$dismissed$$, $$expanded$$, $$celebrated$$, $$Weak evidence leads to a case being dismissed.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 24, $$ENG$$, $$Sentence Completion$$, $$easy$$, $$The manager praised her because she was both efficient and _____.$$, 'A', $$reliable$$, $$careless$$, $$late$$, $$uncertain$$, $$Praise follows positive qualities; reliable fits alongside efficient.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 25, $$ENG$$, $$Sentence Completion$$, $$medium$$, $$The scientist repeated the experiment to _____ the result.$$, 'B', $$ignore$$, $$verify$$, $$hide$$, $$delay$$, $$Repeating an experiment verifies or confirms the result.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 26, $$ENG$$, $$Reading Comprehension$$, $$medium$$, $$A passage says a city reduced traffic by improving public transport. The main idea is that:$$, 'B', $$cars are always harmful$$, $$public transport can help reduce traffic$$, $$cities should stop all travel$$, $$roads are unnecessary$$, $$The supporting evidence points to public transport reducing traffic.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 27, $$ENG$$, $$Reading Comprehension$$, $$easy$$, $$A paragraph gives three examples to support one claim. The examples mainly serve as:$$, 'A', $$evidence$$, $$contradictions$$, $$headings$$, $$questions$$, $$Examples function as evidence supporting the claim.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 28, $$ENG$$, $$Reading Comprehension$$, $$medium$$, $$An author uses statistics to support an argument. The statistics function mainly as:$$, 'A', $$evidence$$, $$humor$$, $$fiction$$, $$decoration$$, $$Statistics provide evidence to strengthen an argument.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 29, $$ENG$$, $$Reading Comprehension$$, $$easy$$, $$The tone of a passage praising a successful project is most likely:$$, 'B', $$critical$$, $$positive$$, $$indifferent$$, $$hostile$$, $$Praising indicates a positive tone.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 30, $$ENG$$, $$Reading Comprehension$$, $$easy$$, $$If an author says "however", the word usually signals:$$, 'B', $$addition$$, $$contrast$$, $$cause$$, $$time$$, $$"However" introduces a contrasting point.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 31, $$ENG$$, $$Analogies$$, $$easy$$, $$Book is to reading as fork is to:$$, 'B', $$writing$$, $$eating$$, $$drawing$$, $$sleeping$$, $$Book is used for reading; fork is used for eating.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 32, $$ENG$$, $$Analogies$$, $$easy$$, $$Bird is to nest as bee is to:$$, 'B', $$cave$$, $$hive$$, $$pond$$, $$web$$, $$A bird lives in a nest; a bee lives in a hive.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 33, $$ENG$$, $$Analogies$$, $$easy$$, $$Doctor is to hospital as teacher is to:$$, 'B', $$court$$, $$school$$, $$factory$$, $$airport$$, $$A doctor works in a hospital; a teacher works in a school.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 34, $$ENG$$, $$Analogies$$, $$medium$$, $$Seed is to plant as egg is to:$$, 'B', $$stone$$, $$animal$$, $$soil$$, $$water$$, $$A seed grows into a plant; an egg hatches into an animal.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 35, $$ENG$$, $$Analogies$$, $$easy$$, $$Hot is to cold as high is to:$$, 'B', $$large$$, $$low$$, $$long$$, $$deep$$, $$Hot and cold are opposites; high and low are opposites.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 36, $$ENG$$, $$Vocabulary$$, $$medium$$, $$Choose the correctly used word:$$, 'B', $$The medicine effected his recovery.$$, $$The medicine affected his recovery.$$, $$The medicine affect his recovery.$$, $$The medicine affecting his recovery.$$, $$"Affected" (changed/influenced) is correct here; "effected" means brought about.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 37, $$ENG$$, $$Vocabulary$$, $$medium$$, $$Choose the correct word: "Everyone _____ Ahmed was absent."$$, 'A', $$except$$, $$accept$$, $$expects$$, $$access$$, $$"Except" means other than / excluding.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 38, $$ENG$$, $$Vocabulary$$, $$easy$$, $$Which pair are homophones?$$, 'D', $$accept/except$$, $$large/large$$, $$quiet/quite$$, $$write/right$$, $$Write and right sound alike but differ in spelling and meaning.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 39, $$ENG$$, $$Grammar$$, $$easy$$, $$Choose the correct comparative form:$$, 'B', $$more better$$, $$better$$, $$best$$, $$gooder$$, $$The comparative of "good" is "better".$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 40, $$ENG$$, $$Tenses$$, $$medium$$, $$"She has been studying for two hours" is in the:$$, 'B', $$present perfect$$, $$present perfect continuous$$, $$past continuous$$, $$future perfect$$, $$"Has been + -ing" marks the present perfect continuous.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 41, $$ENG$$, $$Direct-Indirect Speech$$, $$medium$$, $$He said, "I am tired." In reported speech:$$, 'B', $$He said that I am tired.$$, $$He said that he was tired.$$, $$He says that he was tired.$$, $$He said that he is tired yesterday.$$, $$Pronouns and tense shift back: "I am" becomes "he was".$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 42, $$ENG$$, $$Vocabulary$$, $$medium$$, $$"Meticulous" describes someone who is:$$, 'B', $$careless$$, $$very careful$$, $$impatient$$, $$dishonest$$, $$Meticulous means extremely careful and thorough.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 43, $$ENG$$, $$Vocabulary$$, $$medium$$, $$"Ambiguous" means:$$, 'B', $$having one clear meaning$$, $$open to more than one interpretation$$, $$very short$$, $$completely false$$, $$Ambiguous means having multiple possible interpretations.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 1, 44, $$ENG$$, $$Vocabulary$$, $$medium$$, $$"Concise" means:$$, 'A', $$brief and clear$$, $$long and confusing$$, $$angry$$, $$unrelated$$, $$Concise means giving information briefly and clearly.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 45, $$QUANT$$, $$Percentages$$, $$easy$$, $$What is 15% of 240?$$, 'B', $$24$$, $$36$$, $$40$$, $$48$$, $$15% of 240 = 0.15 × 240 = 36.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 46, $$QUANT$$, $$Algebra$$, $$easy$$, $$If 3x + 5 = 20, x equals:$$, 'B', $$3$$, $$5$$, $$7$$, $$15$$, $$3x = 15, so x = 5.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 47, $$QUANT$$, $$Ratios and Proportions$$, $$easy$$, $$The ratio 18:24 simplifies to:$$, 'B', $$2:3$$, $$3:4$$, $$4:3$$, $$6:8$$, $$Divide both terms by 6: 3:4.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 48, $$QUANT$$, $$Percentages$$, $$easy$$, $$A shirt costing Rs. 2000 is discounted by 15%. What is the sale price?$$, 'B', $$Rs. 1600$$, $$Rs. 1700$$, $$Rs. 1750$$, $$Rs. 1850$$, $$15% of 2000 = 300; 2000 − 300 = 1700.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 49, $$QUANT$$, $$Arithmetic$$, $$easy$$, $$The average of 8, 12, 15 and 5 is:$$, 'B', $$8$$, $$10$$, $$12$$, $$15$$, $$Sum = 40; 40 ÷ 4 = 10.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 50, $$QUANT$$, $$Time and Work$$, $$medium$$, $$5 workers complete a task in 12 days. At the same rate, 10 workers need:$$, 'B', $$3 days$$, $$6 days$$, $$12 days$$, $$24 days$$, $$Doubling workers halves the time: 6 days.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 51, $$QUANT$$, $$Algebra$$, $$easy$$, $$If x² = 49 and x is positive, x =$$, 'C', $$-7$$, $$0$$, $$7$$, $$49$$, $$The positive square root of 49 is 7.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 52, $$QUANT$$, $$Algebra$$, $$easy$$, $$Simplify: 2(x + 3) − x$$, 'B', $$x+3$$, $$x+6$$, $$2x+3$$, $$x-6$$, $$2x + 6 − x = x + 6.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 53, $$QUANT$$, $$Algebra$$, $$medium$$, $$If x + y = 10 and x − y = 4, x =$$, 'C', $$3$$, $$6$$, $$7$$, $$14$$, $$Add the equations: 2x = 14, so x = 7.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 54, $$QUANT$$, $$Algebra$$, $$medium$$, $$The roots of x² − 5x + 6 = 0 are:$$, 'B', $$1,6$$, $$2,3$$, $$-2,-3$$, $$3,5$$, $$Factorise: (x−2)(x−3) = 0, roots 2 and 3.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 55, $$QUANT$$, $$Percentages$$, $$medium$$, $$A number increased by 20% becomes 144. The original number is:$$, 'B', $$115$$, $$120$$, $$124$$, $$132$$, $$144 ÷ 1.20 = 120.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 56, $$QUANT$$, $$Profit and Loss$$, $$medium$$, $$An item bought for Rs. 800 is sold for Rs. 920. The profit percentage is:$$, 'C', $$10%$$, $$12%$$, $$15%$$, $$20%$$, $$Profit = 120; 120/800 × 100 = 15%.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 57, $$QUANT$$, $$Geometry$$, $$easy$$, $$The area of a rectangle 12 cm long and 5 cm wide is:$$, 'C', $$17 cm²$$, $$34 cm²$$, $$60 cm²$$, $$120 cm²$$, $$Area = length × width = 60 cm².$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 58, $$QUANT$$, $$Geometry$$, $$easy$$, $$The perimeter of a square with side 9 cm is:$$, 'C', $$18 cm$$, $$27 cm$$, $$36 cm$$, $$81 cm$$, $$Perimeter = 4 × side = 36 cm.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 59, $$QUANT$$, $$Geometry$$, $$easy$$, $$The angles of a triangle sum to:$$, 'B', $$90°$$, $$180°$$, $$270°$$, $$360°$$, $$The interior angles of any triangle sum to 180°.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 60, $$QUANT$$, $$Probability$$, $$easy$$, $$A fair coin is tossed once. The probability of heads is:$$, 'C', $$0$$, $$1/4$$, $$1/2$$, $$1$$, $$One favourable outcome out of two equally likely: 1/2.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 61, $$QUANT$$, $$Probability$$, $$easy$$, $$A fair die is rolled. The probability of an even number is:$$, 'C', $$1/6$$, $$1/3$$, $$1/2$$, $$2/3$$, $$Three even faces (2,4,6) out of six: 3/6 = 1/2.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 62, $$QUANT$$, $$Sequences and Series$$, $$medium$$, $$What is the next term: 2, 6, 12, 20, 30, ?$$, 'C', $$36$$, $$40$$, $$42$$, $$44$$, $$Differences increase by 2 each step (4,6,8,10,12): 30 + 12 = 42.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 63, $$QUANT$$, $$Sequences and Series$$, $$easy$$, $$What is the next term: 3, 9, 27, 81, ?$$, 'B', $$162$$, $$243$$, $$324$$, $$729$$, $$Each term multiplies by 3: 81 × 3 = 243.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 64, $$QUANT$$, $$Speed Distance Time$$, $$easy$$, $$A car travels 180 km in 3 hours. Its average speed is:$$, 'B', $$50 km/h$$, $$60 km/h$$, $$70 km/h$$, $$90 km/h$$, $$Speed = distance ÷ time = 60 km/h.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 65, $$QUANT$$, $$Arithmetic$$, $$easy$$, $$A machine produces 120 items in 4 hours. Its rate is:$$, 'B', $$20/hour$$, $$30/hour$$, $$40/hour$$, $$60/hour$$, $$Rate = 120 ÷ 4 = 30 items per hour.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 66, $$QUANT$$, $$Arithmetic$$, $$medium$$, $$The greatest common divisor of 36 and 48 is:$$, 'C', $$6$$, $$8$$, $$12$$, $$16$$, $$The largest number dividing both is 12.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 2, 67, $$QUANT$$, $$Arithmetic$$, $$easy$$, $$The least common multiple of 6 and 8 is:$$, 'C', $$12$$, $$18$$, $$24$$, $$48$$, $$Multiples: 6,12,18,24 and 8,16,24 → LCM 24.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 68, $$ANALY$$, $$Number Patterns$$, $$easy$$, $$Find the next number: 5, 10, 20, 40, ?$$, 'C', $$50$$, $$60$$, $$80$$, $$100$$, $$Each term doubles: 40 × 2 = 80.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 69, $$ANALY$$, $$Number Patterns$$, $$easy$$, $$Find the next number: 1, 4, 9, 16, ?$$, 'C', $$20$$, $$24$$, $$25$$, $$36$$, $$These are squares: 1,4,9,16,25.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 70, $$ANALY$$, $$Letter Patterns$$, $$medium$$, $$Find the next letter: A, C, F, J, ?$$, 'C', $$M$$, $$N$$, $$O$$, $$P$$, $$Gaps increase by one each step (+2,+3,+4,+5): J + 5 = O.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 71, $$ANALY$$, $$Coding Decoding$$, $$easy$$, $$If CAT is coded as DBU, DOG is coded as:$$, 'A', $$EPH$$, $$EOG$$, $$DPH$$, $$FPH$$, $$Each letter shifts one forward: D→E, O→P, G→H = EPH.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 72, $$ANALY$$, $$Coding Decoding$$, $$medium$$, $$If SOUTH is coded as TPVUI, NORTH is coded as:$$, 'A', $$OPSUI$$, $$OPSTI$$, $$OPSGI$$, $$NQSTI$$, $$Each letter shifts one forward: N→O, O→P, R→S, T→U, H→I = OPSUI.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 73, $$ANALY$$, $$Logic Puzzles$$, $$easy$$, $$A person walks 5 km north, then 3 km east. In which general direction are they from the start?$$, 'B', $$North-west$$, $$North-east$$, $$South-east$$, $$South-west$$, $$Net displacement is north plus east, i.e. north-east.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 74, $$ANALY$$, $$Logic Puzzles$$, $$easy$$, $$Ali faces east and turns right twice. He now faces:$$, 'D', $$North$$, $$South$$, $$East$$, $$West$$, $$East → right = South; right again = West.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 75, $$ANALY$$, $$Logic Puzzles$$, $$easy$$, $$A is the brother of B. B is the sister of C. How is A related to C?$$, 'A', $$Brother$$, $$Sister$$, $$Father$$, $$Uncle$$, $$A and C are siblings, so A (male) is C's brother.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 76, $$ANALY$$, $$Logic Puzzles$$, $$easy$$, $$Sara is the daughter of Ahmed. Ahmed is the son of Zaid. Zaid is Sara's:$$, 'C', $$Father$$, $$Brother$$, $$Grandfather$$, $$Uncle$$, $$Ahmed's father is Sara's grandfather.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 77, $$ANALY$$, $$Logical Ordering$$, $$easy$$, $$Five students A, B, C, D, E stand in a line: A before B, B before C, C before D, D before E. Who is third?$$, 'C', $$A$$, $$B$$, $$C$$, $$D$$, $$Order is A,B,C,D,E; the third is C.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 78, $$ANALY$$, $$Logical Ordering$$, $$easy$$, $$P is taller than Q, Q taller than R, R taller than S. Who is shortest?$$, 'D', $$P$$, $$Q$$, $$R$$, $$S$$, $$Each is taller than the next, so S is shortest.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 79, $$ANALY$$, $$Syllogisms$$, $$medium$$, $$All roses are flowers. Some flowers fade quickly. Which conclusion is definitely true?$$, 'C', $$All roses fade quickly.$$, $$Some roses are not flowers.$$, $$Roses are flowers.$$, $$No flowers are roses.$$, $$The first premise directly states roses are flowers.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 80, $$ANALY$$, $$Syllogisms$$, $$easy$$, $$All cats are mammals. All mammals are animals. Therefore:$$, 'B', $$All animals are cats.$$, $$All cats are animals.$$, $$No cats are animals.$$, $$Some animals are not mammals.$$, $$Cats ⊂ mammals ⊂ animals, so all cats are animals.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 81, $$ANALY$$, $$Logic Puzzles$$, $$easy$$, $$A, B, C and D sit around a table. A sits opposite C; B sits opposite D. Who is opposite A?$$, 'B', $$B$$, $$C$$, $$D$$, $$Cannot determine$$, $$Directly stated: A is opposite C.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 82, $$ANALY$$, $$Classification$$, $$easy$$, $$Which is different?$$, 'C', $$Triangle$$, $$Square$$, $$Circle$$, $$Rectangle$$, $$Circle has no straight edges; the rest are polygons.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 83, $$ANALY$$, $$Classification$$, $$easy$$, $$Which number does not belong?$$, 'D', $$9$$, $$16$$, $$25$$, $$30$$, $$9, 16, 25 are perfect squares; 30 is not.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 84, $$ANALY$$, $$Syllogisms$$, $$easy$$, $$If all books are useful and this object is a book, then the object is:$$, 'A', $$useful$$, $$expensive$$, $$old$$, $$large$$, $$The object inherits the property of books: useful.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 85, $$ANALY$$, $$Logic Puzzles$$, $$medium$$, $$If today is Monday, what day will it be after 10 days?$$, 'B', $$Wednesday$$, $$Thursday$$, $$Friday$$, $$Saturday$$, $$10 days = one week (Monday) + 3 days = Thursday.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 86, $$ANALY$$, $$Logic Puzzles$$, $$easy$$, $$At exactly 3:00, the angle between the clock hands is:$$, 'C', $$0°$$, $$30°$$, $$90°$$, $$180°$$, $$Minute hand at 12, hour hand at 3 — a quarter turn: 90°.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 87, $$ANALY$$, $$Logical Ordering$$, $$medium$$, $$In a class of 30 students, Ali is 7th from the top. His position from the bottom is:$$, 'C', $$22nd$$, $$23rd$$, $$24th$$, $$25th$$, $$30 − 7 + 1 = 24th.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 88, $$ANALY$$, $$Critical Reasoning$$, $$hard$$, $$Three boxes labelled Apples, Oranges and Mixed all have wrong labels. From which box should you pick one fruit first?$$, 'C', $$Apples$$, $$Oranges$$, $$Mixed$$, $$Any box$$, $$Since all labels are wrong, the "Mixed" box contains only one fruit type, identifying it fixes the rest.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 3, 89, $$ANALY$$, $$Syllogisms$$, $$hard$$, $$If some A are B and all B are C, which must be true?$$, 'B', $$All A are C.$$, $$Some A are C.$$, $$No A are C.$$, $$All C are A.$$, $$The A that are B are also C, so some A are C.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 4, 90, $$PHY$$, $$Mechanics$$, $$easy$$, $$The SI unit of force is:$$, 'B', $$Joule$$, $$Newton$$, $$Watt$$, $$Pascal$$, $$Force is measured in newtons (N).$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 4, 91, $$PHY$$, $$Mechanics$$, $$easy$$, $$Acceleration is the rate of change of:$$, 'B', $$distance$$, $$velocity$$, $$mass$$, $$force$$, $$Acceleration = change in velocity per unit time.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 4, 92, $$PHY$$, $$Mechanics$$, $$easy$$, $$A body moving at constant velocity has:$$, 'A', $$zero acceleration$$, $$increasing acceleration$$, $$negative mass$$, $$zero speed$$, $$Constant velocity means no change in velocity → zero acceleration.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 4, 93, $$PHY$$, $$Mechanics$$, $$easy$$, $$Momentum is equal to:$$, 'B', $$m/a$$, $$mv$$, $$ma$$, $$m/v$$, $$Momentum p = mass × velocity = mv.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 4, 94, $$PHY$$, $$Mechanics$$, $$medium$$, $$The kinetic energy of an object depends on its:$$, 'A', $$mass and speed$$, $$mass only$$, $$height only$$, $$temperature only$$, $$KE = ½mv², so it depends on mass and speed.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 4, 95, $$PHY$$, $$Mechanics$$, $$easy$$, $$Work is done when a force causes:$$, 'B', $$mass$$, $$displacement$$, $$temperature$$, $$density$$, $$Work = force × displacement in the direction of force.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 4, 96, $$PHY$$, $$Waves and Sound$$, $$easy$$, $$The SI unit of frequency is:$$, 'B', $$meter$$, $$hertz$$, $$newton$$, $$joule$$, $$Frequency is measured in hertz (Hz).$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 4, 97, $$PHY$$, $$Waves and Sound$$, $$easy$$, $$Sound cannot travel through:$$, 'D', $$air$$, $$water$$, $$steel$$, $$vacuum$$, $$Sound needs a medium; it cannot travel through a vacuum.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 4, 98, $$PHY$$, $$Electricity$$, $$easy$$, $$The SI unit of electric current is:$$, 'C', $$volt$$, $$ohm$$, $$ampere$$, $$watt$$, $$Current is measured in amperes (A).$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 4, 99, $$PHY$$, $$Electricity$$, $$easy$$, $$Ohm's law is:$$, 'A', $$V = IR$$, $$P = VI$$, $$F = ma$$, $$Q = It$$, $$Ohm's law: voltage = current × resistance (V = IR).$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 4, 100, $$PHY$$, $$Electricity$$, $$easy$$, $$Two resistors of 2 Ω and 3 Ω connected in series have total resistance:$$, 'B', $$1 Ω$$, $$5 Ω$$, $$6 Ω$$, $$9 Ω$$, $$Series resistances add: 2 + 3 = 5 Ω.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 4, 101, $$PHY$$, $$Thermodynamics$$, $$easy$$, $$Heat transfer that can occur through a vacuum is:$$, 'C', $$conduction$$, $$convection$$, $$radiation$$, $$diffusion$$, $$Radiation needs no medium and can pass through a vacuum.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 4, 102, $$PHY$$, $$Optics$$, $$easy$$, $$A convex lens generally:$$, 'B', $$diverges parallel rays$$, $$converges parallel rays$$, $$blocks light$$, $$reflects all light$$, $$A convex (converging) lens brings parallel rays together.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 4, 103, $$PHY$$, $$Optics$$, $$medium$$, $$The speed of light is greatest in:$$, 'C', $$glass$$, $$water$$, $$vacuum$$, $$diamond$$, $$Light is fastest in a vacuum; denser media slow it down.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 4, 104, $$PHY$$, $$Electricity$$, $$easy$$, $$The charge of an electron is:$$, 'B', $$positive$$, $$negative$$, $$zero$$, $$variable only$$, $$Electrons carry a negative charge.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 105, $$QUANT$$, $$Algebra$$, $$easy$$, $$If 2x − 7 = 13, x =$$, 'B', $$8$$, $$10$$, $$12$$, $$20$$, $$2x = 20, so x = 10.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 106, $$QUANT$$, $$Algebra$$, $$easy$$, $$Factorize x² − 9:$$, 'A', $$(x-3)(x+3)$$, $$(x-9)(x+1)$$, $$(x-3)²$$, $$(x+9)(x-1)$$, $$Difference of squares: (x−3)(x+3).$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 107, $$QUANT$$, $$Algebra$$, $$easy$$, $$If a = 2 and b = 3, a² + b² =$$, 'C', $$10$$, $$12$$, $$13$$, $$15$$, $$4 + 9 = 13.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 108, $$QUANT$$, $$Algebra$$, $$easy$$, $$Simplify (x²)(x³):$$, 'A', $$x⁵$$, $$x⁶$$, $$2x⁵$$, $$x⁶/2$$, $$Add exponents: x^(2+3) = x⁵.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 109, $$QUANT$$, $$Algebra$$, $$easy$$, $$If x/4 = 6, x =$$, 'C', $$10$$, $$20$$, $$24$$, $$30$$, $$x = 6 × 4 = 24.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 110, $$QUANT$$, $$Algebra$$, $$easy$$, $$Solve: 5x + 2 = 3x + 14.$$, 'C', $$4$$, $$5$$, $$6$$, $$8$$, $$2x = 12, so x = 6.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 111, $$QUANT$$, $$Algebra$$, $$medium$$, $$The discriminant of x² − 4x + 4 is:$$, 'A', $$0$$, $$4$$, $$8$$, $$16$$, $$b² − 4ac = 16 − 16 = 0 (equal roots).$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 112, $$QUANT$$, $$Algebra$$, $$medium$$, $$The roots of x² − 7x + 12 = 0 are:$$, 'B', $$2 and 6$$, $$3 and 4$$, $$1 and 12$$, $$-3 and -4$$, $$Factorise: (x−3)(x−4) = 0 → 3 and 4.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 113, $$QUANT$$, $$Algebra$$, $$easy$$, $$If f(x) = 2x + 1, f(4) = ?$$, 'C', $$7$$, $$8$$, $$9$$, $$10$$, $$f(4) = 2(4) + 1 = 9.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 114, $$QUANT$$, $$Algebra$$, $$easy$$, $$If f(x) = x², f(−3) = ?$$, 'D', $$-9$$, $$-6$$, $$6$$, $$9$$, $$f(−3) = (−3)² = 9.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 115, $$QUANT$$, $$Algebra$$, $$easy$$, $$2³ × 2² =$$, 'C', $$16$$, $$24$$, $$32$$, $$64$$, $$Add exponents: 2⁵ = 32.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 116, $$QUANT$$, $$Algebra$$, $$medium$$, $$(3²)³ =$$, 'C', $$27$$, $$81$$, $$243$$, $$729$$, $$Multiply exponents: 3⁶ = 729.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 117, $$QUANT$$, $$Algebra$$, $$easy$$, $$log₁₀(1000) =$$, 'C', $$1$$, $$2$$, $$3$$, $$10$$, $$10³ = 1000, so log₁₀1000 = 3.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 118, $$QUANT$$, $$Algebra$$, $$easy$$, $$If A = {1,2,3} and B = {3,4,5}, A ∩ B is:$$, 'B', $${1,2}$$, $${3}$$, $${4,5}$$, $${1,2,3,4,5}$$, $$Intersection contains elements in both sets: {3}.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 119, $$QUANT$$, $$Algebra$$, $$medium$$, $$If a set has 4 elements, its power set has:$$, 'D', $$4$$, $$8$$, $$12$$, $$16$$, $$Power set size = 2⁴ = 16.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 120, $$QUANT$$, $$Geometry$$, $$easy$$, $$A right triangle has legs 3 and 4. The hypotenuse is:$$, 'A', $$5$$, $$6$$, $$7$$, $$8$$, $$√(3² + 4²) = √25 = 5.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 121, $$QUANT$$, $$Geometry$$, $$easy$$, $$Area of a circle with radius 7 cm (π = 22/7) is:$$, 'C', $$44$$, $$88$$, $$154$$, $$308$$, $$πr² = (22/7)(7²) = 154 cm².$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 122, $$QUANT$$, $$Geometry$$, $$easy$$, $$Circumference of a circle with radius 7 cm (π = 22/7) is:$$, 'B', $$22$$, $$44$$, $$88$$, $$154$$, $$2πr = 2(22/7)(7) = 44 cm.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 123, $$QUANT$$, $$Geometry$$, $$medium$$, $$The diagonal of a square of side 5 is:$$, 'C', $$5$$, $$10$$, $$5√2$$, $$25$$, $$Diagonal = side × √2 = 5√2.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 124, $$QUANT$$, $$Geometry$$, $$easy$$, $$Volume of a cube with side 4 cm is:$$, 'C', $$16$$, $$32$$, $$64$$, $$128$$, $$Volume = 4³ = 64 cm³.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 125, $$QUANT$$, $$Geometry$$, $$easy$$, $$sin 30° equals:$$, 'B', $$0$$, $$1/2$$, $$√2/2$$, $$1$$, $$sin 30° = 1/2.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 126, $$QUANT$$, $$Geometry$$, $$easy$$, $$cos 60° equals:$$, 'B', $$0$$, $$1/2$$, $$√3/2$$, $$1$$, $$cos 60° = 1/2.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 127, $$QUANT$$, $$Geometry$$, $$easy$$, $$tan 45° equals:$$, 'C', $$0$$, $$1/2$$, $$1$$, $$√3$$, $$tan 45° = 1.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 128, $$QUANT$$, $$Geometry$$, $$medium$$, $$If sin θ = 3/5 for an acute angle θ, cos θ =$$, 'B', $$3/5$$, $$4/5$$, $$5/3$$, $$1/5$$, $$Adjacent = √(5²−3²) = 4, so cos θ = 4/5.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 129, $$QUANT$$, $$Geometry$$, $$easy$$, $$The slope of y = 3x + 2 is:$$, 'B', $$2$$, $$3$$, $$-3$$, $$1/3$$, $$In y = mx + c, the slope m = 3.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 130, $$QUANT$$, $$Geometry$$, $$easy$$, $$The x-coordinate of the point (4, −2) is:$$, 'C', $$-2$$, $$2$$, $$4$$, $$6$$, $$In (x, y), the first value is the x-coordinate: 4.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 131, $$QUANT$$, $$Geometry$$, $$easy$$, $$Distance between (0,0) and (3,4) is:$$, 'C', $$3$$, $$4$$, $$5$$, $$7$$, $$√(3² + 4²) = 5.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 132, $$QUANT$$, $$Arithmetic$$, $$easy$$, $$What is 2/3 + 1/6?$$, 'C', $$1/2$$, $$2/3$$, $$5/6$$, $$1$$, $$4/6 + 1/6 = 5/6.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 133, $$QUANT$$, $$Arithmetic$$, $$easy$$, $$What is 5/8 − 1/4?$$, 'B', $$1/8$$, $$3/8$$, $$1/2$$, $$5/12$$, $$5/8 − 2/8 = 3/8.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 134, $$QUANT$$, $$Arithmetic$$, $$easy$$, $$0.25 as a fraction is:$$, 'C', $$1/2$$, $$1/3$$, $$1/4$$, $$1/5$$, $$0.25 = 25/100 = 1/4.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 135, $$QUANT$$, $$Arithmetic$$, $$easy$$, $$The reciprocal of 2/5 is:$$, 'B', $$2/5$$, $$5/2$$, $$-5/2$$, $$3/5$$, $$Reciprocal flips the fraction: 5/2.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 136, $$QUANT$$, $$Percentages$$, $$easy$$, $$A value of 500 increases by 10%. The new value is:$$, 'C', $$510$$, $$540$$, $$550$$, $$600$$, $$500 × 1.10 = 550.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 137, $$QUANT$$, $$Ratios and Proportions$$, $$easy$$, $$If x:y = 2:5 and y = 20, x = ?$$, 'B', $$4$$, $$8$$, $$10$$, $$12$$, $$x = (2/5) × 20 = 8.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 138, $$QUANT$$, $$Arithmetic$$, $$easy$$, $$The average of 10, 20, 30, 40 and 50 is:$$, 'B', $$25$$, $$30$$, $$35$$, $$40$$, $$Sum = 150; 150 ÷ 5 = 30.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 139, $$QUANT$$, $$Probability$$, $$easy$$, $$A bag contains 3 red and 2 blue balls. Probability of drawing a red ball is:$$, 'B', $$2/5$$, $$3/5$$, $$1/2$$, $$3/2$$, $$3 favourable out of 5: 3/5.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 140, $$QUANT$$, $$Probability$$, $$medium$$, $$Two fair coins are tossed. Probability of two heads is:$$, 'C', $$1/2$$, $$1/3$$, $$1/4$$, $$1/8$$, $$One favourable (HH) out of four outcomes: 1/4.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 141, $$QUANT$$, $$Probability$$, $$easy$$, $$How many ways can 3 different books be arranged on a shelf?$$, 'B', $$3$$, $$6$$, $$9$$, $$12$$, $$3! = 3 × 2 × 1 = 6.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 142, $$QUANT$$, $$Probability$$, $$medium$$, $$How many ways can 2 students be chosen from 5?$$, 'C', $$5$$, $$8$$, $$10$$, $$20$$, $$₅C₂ = 5!/(2!3!) = 10.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 143, $$QUANT$$, $$Sequences and Series$$, $$easy$$, $$The nth term of 2, 4, 6, 8, ... is:$$, 'B', $$n$$, $$2n$$, $$n+2$$, $$2n+2$$, $$Terms are even numbers: 2n.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 144, $$QUANT$$, $$Sequences and Series$$, $$easy$$, $$The sum of the first 10 positive integers is:$$, 'C', $$45$$, $$50$$, $$55$$, $$60$$, $$n(n+1)/2 = 10(11)/2 = 55.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 145, $$QUANT$$, $$Algebra$$, $$medium$$, $$The determinant of [[2,1],[3,4]] is:$$, 'A', $$5$$, $$6$$, $$8$$, $$11$$, $$(2×4) − (1×3) = 8 − 3 = 5.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 146, $$QUANT$$, $$Algebra$$, $$medium$$, $$The derivative of x² is:$$, 'B', $$x$$, $$2x$$, $$x²/2$$, $$2$$, $$d/dx x² = 2x.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 147, $$QUANT$$, $$Algebra$$, $$easy$$, $$The derivative of a constant is:$$, 'C', $$1$$, $$the constant$$, $$0$$, $$undefined$$, $$The derivative of any constant is 0.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 148, $$QUANT$$, $$Algebra$$, $$medium$$, $$∫ 2x dx equals:$$, 'B', $$2x²+C$$, $$x²+C$$, $$x+C$$, $$2+C$$, $$∫2x dx = x² + C.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 5, 149, $$QUANT$$, $$Statistics$$, $$easy$$, $$The median of 2, 5, 7, 9, 12 is:$$, 'B', $$5$$, $$7$$, $$9$$, $$12$$, $$Five ordered values; the middle one is 7.$$);
select "public"."seed_mock_question"($$Bahria University — Extended Mock Test$$, $$150 MCQs · 120 minutes · 1 mark each · no negative marking$$, 6, 150, $$QUANT$$, $$Arithmetic$$, $$easy$$, $$When 17 is divided by 5, the remainder is:$$, 'A', $$2$$, $$3$$, $$4$$, $$5$$, $$17 = 5×3 + 2, so the remainder is 2.$$);
